### PR TITLE
Framework upgrades

### LINKED ISSUE #98: RuntimeException when running CDI-Unit with WELD 2.3.5.Final
I'm trying to run CDI unit tests with the WELD implementation used by WildFly 10.1.0.Final but I receive the following exception:

java.lang.NoClassDefFoundError: org/jboss/weld/environment/ContainerInstanceFactory

I'm testing with cdi-unit 3.1.4 and JUnit 4.12 but the problem occurs also with version 3.1.4

### PR DESCRIPTION
**Pull request by sventorben**
See commit history for a full list of updates.

I would like to use this as a base for implementing support of JUnit 5 (issue #103)  when junit-team/junit5#672 has been implemented.

Should also fix #98  and #101

### CODE REVIEW

**Comment by zeitiger** [comment]
I also like to see this pull request merged soon, because my project stuck on a bug with Java 8 default methods in connection with old versions of weld.

File: cdi-unit-tests/src/test/java/org/jglue/cdiunit/TestContextController.java [hunk 1]
```diff
@@ -62,7 +62,7 @@ public Integer call() throws Exception {
 
 	@Produces
 	@RequestScoped
-	private TestCounter createTestCounter() {
+	TestCounter createTestCounter() {
```
Comment (seanf) [inline cdi-unit-tests/src/test/java/org/jglue/cdiunit/TestContextController.java]: Why the scope change?

File: cdi-unit/pom.xml [hunk 2]
```diff
@@ -35,27 +35,24 @@
 		<dependency>
 			<groupId>org.jboss.weld.se</groupId>
 			<artifactId>weld-se-core</artifactId>
-			<scope>compile</scope>
-			<version>2.3.4.Final</version>
+			<version>2.4.2.SP1</version>
+			<scope>provided</scope>
```
Comment (seanf) [inline cdi-unit/pom.xml]: This is basically fixing a scoping mistake, is that right? If another project uses cdi-unit with test scope, it won't make any difference, but if it uses it with compile scope (for some reason), this will keep weld-se-core off the classpath, which is probably a good thing.

**Comment by seanf** [comment]
@BrynCooke Do you have any objections to bumping the version of CDI-Unit to 4.0.0, required Java to 1.8, and required Weld to 2.x?

File: .travis.yml [hunk 3]
```diff
@@ -36,8 +36,8 @@ env:
     - WELD_VERSION=2.0.3.Final
     - WELD_VERSION=2.0.2.Final
     - WELD_VERSION=2.0.1.Final
-    - WELD_VERSION=1.1.16.Final
-    - WELD_VERSION=1.1.15.Final
+  #  - WELD_VERSION=1.1.16.Final
+  #  - WELD_VERSION=1.1.15.Final
```
Comment (seanf) [inline .travis.yml]: @sventorben If we're getting rid of Weld 1.x support, these should just go. And so should the file Weld11TestUrlDeployment.java. Thanks!

**Comment by zeitiger** [comment]
What is the state? Will this pull request be merged or not?

File: cdi-unit-tests/src/test/java/org/jglue/cdiunit/TestContextController.java (hunk 1 above)
Comment (seanf) [inline cdi-unit-tests/src/test/java/org/jglue/cdiunit/TestContextController.java]: Looks like this fixes these tests which have been breaking in Travis:

    testAsynchronousExecution(org.jglue.cdiunit.TestContextController)
    testSynchronousExecution(org.jglue.cdiunit.TestContextController)

**Comment by seanf** [comment]
Thanks for the PR @sventorben. I want to get #96 (#107) and #106 into release 4.0 as well. Once I see their rebuilds pass, I'll merge them and ask @BrynCooke to make the release.

**Comment by seanf** [comment]
The 4.0.0 release is tracked as #108.
